[project]
name = "ai-fastapi-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.31.0",
    "fastapi>=0.141.1",
    "greenlet>=3.5.5",
    "pydantic-settings>=2.15.0",
    "requests>=2.34.2",
    "sqlalchemy>=2.0.52",
    "uvicorn[standard]>=0.52.4",
]
[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["app/tests"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
